name: LostShardK
main: com.github.kotooriiii.LostShardPlugin
author: kotooriiii
depend: [LuckPerms, PacketListenerApi, Citizens, ProtocolLib]
softdepend:
  - WorldBorder
  - HolographicDisplays
loadbefore:
  - BuycraftX
version: 1.0
api-version: 1.16
commands:
  spell:
    aliases:
      - spells
  sorcery:
  toggle:
  spellbook:
  enchant:
  announce:
  who:
    aliases:
      - playerlist
      - players
  tips:
  discord:
  tutorial:
  skip:
  ignore:
  staff:
    aliases:
      - st
  build:
  ffa:
  join:
  leave:
  atone:
  scroll:
    aliases:
      - scrolls
  playtime:
  removeoldentities:
  notification:
    aliases:
      - notif
  private:
  public:
  doc:
  wiki:
  youtube:
    aliases:
      - yt
  book:
  adminchat:
  clearchat:
  clearchatall:
  lostshard:
    aliases:
      - ls
  ff:
    description:
    usage:
    aliases:
      - friendlyfire
  clan:
    description:
    usage:
    aliases:
      - clans
      - c
  hostility:
    description:
    usage:
    aliases:
      - host
  guard:
    description:
    usage:
    aliases:
      - guards
  hud:
  #Bank
  chest:
    description:
    usage:
  bank:
    description:
    usage:
  withdraw:
    description:
    usage:
  deposit:
    description:
    usage:
  balance:
    description:
    usage:
    aliases:
      - bal
  #Sale
  buy:
    description:
    usage:
  sell:
    description:
    usage:
  price:
    description:
    usage:
  #Runebook stuff
  bind:
  cast:
  mark:
    description:
    usage:
    aliases:
      - marks

  #stat stuff
  stat:
    description:
    usage:
    aliases:
      - stats
  meditate:
  rest:
  addtitle:
  addtitlegold:
  addrank:

  #skill stuff
  archery:
  swordsmanship:
  mining:
  fishing:
  blacksmithy:

  smithing:
  smelt:
  enhance:
  harden:
  power:
  sharpen:
  repair:
  ignite:
  taming:
  pets:
  brawling:
  survivalism:
  camp:
  track:
  skills:
    description:
    usage:
    aliases:
      - skill
  #plot stuff
  plot:
    aliases:
      - plots
  spawn:

  #chat, also clan is chat
  local:
  global:
    description:
    usage:
    aliases:
      - g
  shout:
    aliases:
      - s
  whisper:
    aliases:
      - w
  msg:
    description:
    usage:
    aliases:
      - message
  mute:
  heal:
  banmatch:
    description:
    usage:
    aliases:
      - bm
  moneymatch:
    description:
    usage:
    aliases:
      - mm
  ban:
  unban:
  invsee:
  murdercount:
  donate:
  reply:
    description:
    usage:
    aliases:
      - r
  #Discord
  opt:
  suicide:
    description:
    usage:
    aliases:
      - kill
  whois:



