name: LostShardK
main: com.github.kotooriiii.LostShardK
author: kotooriiii
version: 1.0
api-version: 1.15
commands:
  ff:
    description:
    usage:
    aliases:
      - friendlyfire
  clan:
    description:
    usage:
    aliases:
      - clans
  hostility:
    description:
    usage:
    aliases:
      - host
  guards:
    description:
    usage:
    aliases:
      - guards