name: LostShardK
main: com.github.kotooriiii.LostShardPlugin
author: kotooriiii
depend: [LuckPerms]
softdepend:
  - WorldBorder
loadbefore:
  - BuycraftX

version: 1.0
api-version: 1.15
commands:
  ff:
    description:
    usage:
    aliases:
      - friendlyfire
  clan:
    description:
    usage:
    aliases:
      - clans
      - c
  hostility:
    description:
    usage:
    aliases:
      - host
  guard:
    description:
    usage:
    aliases:
      - guards
  hud:
  #Bank
  chest:
    description:
    usage:
  bank:
    description:
    usage:
  withdraw:
    description:
    usage:
  deposit:
    description:
    usage:
  balance:
    description:
    usage:
    aliases:
      - bal
  #Sale
  buy:
    description:
    usage:
  sell:
    description:
    usage:
  price:
    description:
    usage:
  #Runebook stuff
  bind:
  cast:
  mark:
    description:
    usage:
    aliases:
      - marks

  #stat stuff
  stat:
    description:
    usage:
    aliases:
      - stats
  meditate:
  rest:
  addtitle:
  addrank:

  #skill stuff
  archery:
  swordsmanship:
  mining:
  fishing:

  smithing:
  smelt:
  enhance:
  harden:
  power:
  sharpen:
  repair:

  taming:
  pets:

  brawling:

  survivalism:
  camp:
  track:



  skills:
    description:
    usage:
    aliases:
      - skill

  #plot stuff
  plot:
    aliases:
      - plots
  spawn:

  #chat, also clan is chat
  global:
    description:
    usage:
    aliases:
      - g
  local:
    description:
    usage:
    aliases:
      - l
  msg:
    description:
    usage:
    aliases:
      - message
  mute:
  heal:
  banmatch:
    description:
    usage:
    aliases:
      - bm
  moneymatch:
    description:
    usage:
    aliases:
      - mm
  ban:
  unban:
  invsee:
  murdercount:
  donate:
  reply:
    description:
    usage:
    aliases:
      - r
  #Discord
  opt:
  suicide:
    description:
    usage:
    aliases:
      - kill
  whois:



