name: LostShardK
main: com.github.kotooriiii.LostShardPlugin
author: kotooriiii
depend: [Vault, LuckPerms]
version: 1.0
api-version: 1.15
commands:
  ff:
    description:
    usage:
    aliases:
      - friendlyfire
  clan:
    description:
    usage:
    aliases:
      - clans
      - c
  hostility:
    description:
    usage:
    aliases:
      - host
  guard:
    description:
    usage:
    aliases:
      - guards
  #Bank
  chest:
    description:
    usage:
  bank:
    description:
    usage:
  withdraw:
    description:
    usage:
  deposit:
    description:
    usage:
  balance:
    description:
    usage:
    aliases:
      - bal
  #Sale
  buy:
    description:
    usage:
  sell:
    description:
    usage:
  price:
    description:
    usage:
  #Runebook stuff
  rb:
  runebook:
  bind:
  cast:

  #stat stuff
  stat:
    description:
    usage:
    aliases:
      - stats
  meditate:
  rest:

  #skill stuff
  setlvl:
  archery:
  swords:
  mining:
  fishing:
  addLoot:
  smithing:
  smelt:
  enhance:
  harden:
  power:
  sharpen:
  repair:
  taming:
  brawling:
  setmurdercount:
  setrank:
  skills:

  #plot stuff
  Plot:

  #chat, also clan is chat
  global:
    description:
    usage:
    aliases:
      - g
  local:
    description:
    usage:
    aliases:
      - l
  msg:
    description:
    usage:
    aliases:
      - message



